### ISSUE TITLE
using ansible to deploy into webfaction web apps

### ISSUE THREAD

**Issue by niccolox** [quentinsf/ansible-webfaction#1]
great work, this is exactly what I have been looking for

this is great ! thank you very much

I found these modules while searching for a way to deploy into existing webfaction web apps

I have found this one, which on the surface seems to have some overlap
https://github.com/bitmazk/ansible-webfaction-gunicorn-django

**Comment by quentinsf** [comment]
Thanks, Nicholas - glad you like it!
Yes, I saw that page, and it looks good, but even though supervisor is a good way to run things, I wanted something a bit closer to the 'standard' Webfaction route.

I should really try packaging this up and deploying it to Ansible Galaxy sometime.
