### ISSUE TITLE
Webfaction Ansible module needs type declarations

### ISSUE THREAD

**Issue by joekarasek** [quentinsf/ansible-webfaction#8]
Hi, I'm trying to determine if anyone is maintaining the webfaction module for Ansible. 
Ansible created a bug in several modules by setting the default type of variables to string if no type is defined. https://github.com/ansible/ansible-modules-extras/issues/1732

Should not be a huge fix to add type definitions, but I haven't seen any updates on this here
https://github.com/ansible/ansible-modules-extras

I'm getting errors that looks like this
╰─›ansible-playbook playbook.yml
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default).
This feature will be removed in a
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [webfaction] **************************************************************

TASK [setup] *******************************************************************
ok: [wf-198-58-114-22.webfaction.com]

TASK [Create a test domain] ****************************************************
fatal: [wf-198-58-114-22.webfaction.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to wf-198-58-114-22.webfaction.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Vtqrc7/ansible_module_webfaction_domain.py\", line 170, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Vtqrc7/ansible_module_webfaction_domain.py\", line 134, in main\r\n    positional_args = [session_id, domain_name] + domain_subdomains\r\n**_TypeError: can only concatenate list (not \"str\") to list\r\n_**", "msg": "MODULE FAILURE"}
	to retry, use: --limit @/Users/karasek/Dev/work/TS-Sites/template/playbook.retry

PLAY RECAP *********************************************************************
wf-198-58-114-22.webfaction.com : ok=1    changed=0    unreachable=0    failed=1

**Comment by quentinsf** [comment]
Hi Joe - sorry for the delay on this - I created the module, but haven't been very active with it since, not least because I'm hardly using webfaction now.  But you're right, ansible-modules-extras is the right place to ask about it since that's the master version.  If I get a chance, I'll look into what's behind the problem and change it there.

Apologies for not being more active on it - rather busy here at present!

All the best, 
Quentin
